// Generated by CoffeeScript 1.7.1
(function(doc) {
  var id;
  if (doc.collection == null) {
    return;
  }
  if (doc.collection === "result") {
    return;
  }
  if (doc.curriculumId) {
    id = doc.curriculumId;
    if (doc.collection === "klass") {
      return;
    }
  } else {
    id = doc.assessmentId;
  }
  return emit(id.substr(-5, 5), null);
});
