// Generated by CoffeeScript 1.7.1
(function(doc) {
  var conflict, dKey, docId, _i, _len, _ref, _results;
  if (doc._conflicts == null) {
    return;
  }
  if (doc.collection === "result") {
    return;
  }
  docId = doc.assessmentId || doc.curriculumId;
  dKey = docId.substr(-5, 5);
  emit(dKey, {
    "_id": doc._id,
    "_rev": doc._rev
  });
  _ref = doc._conflicts;
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    conflict = _ref[_i];
    _results.push(emit(dKey, {
      "_id": doc._id,
      "_rev": conflict
    }));
  }
  return _results;
});
