// Generated by CoffeeScript 1.7.1
(function(doc) {
  var subtest, _i, _len, _ref, _ref1, _results;
  if (doc.collection == null) {
    return;
  }
  if (doc.collection !== 'result') {
    return;
  }
  if (((_ref = doc.subtestData) != null ? _ref.length : void 0) == null) {
    return;
  }
  _ref1 = doc.subtestData;
  _results = [];
  for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
    subtest = _ref1[_i];
    if (subtest.prototype === 'complete') {
      _results.push(emit(subtest.data.end_time, null));
    } else {
      _results.push(void 0);
    }
  }
  return _results;
});
