// Generated by CoffeeScript 1.9.3
Tangerine.conf = {
  db_name: "tangerine",
  design_doc: "tangerine",
  tablet_port: 4895,
  groupPrefix: "group-",
  subnet_base: "http://192.168.1."
};

Tangerine.defaults = {
  settings: {
    "groupDDoc": "ojai",
    "language": "en-US",
    "log": [""],
    "groupName": "",
    "groupHost": "http://dev.tangerinecentral.org/db",
    "upPass": "pass"
  }
};
