// Generated by CoffeeScript 1.7.1
(function(doc) {
  var isArchived, rightCollection;
  rightCollection = doc.collection === 'curriculum' || doc.collection === 'assessment';
  if (!rightCollection) {
    return;
  }
  isArchived = doc.archived === "false" || doc.archived === false;
  if (isArchived) {
    return;
  }
  return emit(doc.id, null);
});
