// Generated by CoffeeScript 1.4.0
var AssessmentPrintView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

AssessmentPrintView = (function(_super) {

  __extends(AssessmentPrintView, _super);

  function AssessmentPrintView() {
    return AssessmentPrintView.__super__.constructor.apply(this, arguments);
  }

  AssessmentPrintView.prototype.initialize = function(options) {
    var _this = this;
    this.abortAssessment = false;
    this.index = 0;
    this.model = options.model;
    Tangerine.activity = "assessment print";
    this.subtestViews = [];
    this.model.subtests.sort();
    return this.model.subtests.each(function(model) {
      var subtestView;
      subtestView = new SubtestPrintView({
        model: model,
        parent: _this,
        format: options.format
      });
      subtestView.on("rendered", function(view) {
        return view != null ? typeof view.afterRender === "function" ? view.afterRender() : void 0 : void 0;
      });
      return _this.subtestViews.push(subtestView);
    });
  };

  AssessmentPrintView.prototype.render = function() {
    var _this = this;
    if (this.model.subtests.length === 0) {
      this.$el.append("<h1>Oops...</h1><p>This assessment is blank. Perhaps you meant to add some subtests.</p>");
    } else {
      this.$el.append("        <style>          body{            font-size: 100%;          }          #prototype_wrapper .print-page{            size: 11in 8.5in;             height: 11in;            width: 8.5in;            margin: 0;            page-break-after: always;            overflow: hidden;          }          #prototype_wrapper .print-page table{            table-layout: fixed;          }          #prototype_wrapper .print-page table td{            overflow: hidden;            text-align: center;            padding: 1%;            font-family: Andika;          }        </style>      ");
      _.each(this.subtestViews, function(subtestView) {
        subtestView.render();
        return _this.$el.append(subtestView.el);
      });
    }
    return this.trigger("rendered");
  };

  return AssessmentPrintView;

})(Backbone.View);
