// Generated by CoffeeScript 1.3.3
var AssessmentPrintView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

AssessmentPrintView = (function(_super) {

  __extends(AssessmentPrintView, _super);

  function AssessmentPrintView() {
    return AssessmentPrintView.__super__.constructor.apply(this, arguments);
  }

  AssessmentPrintView.prototype.initialize = function(options) {
    var _this = this;
    this.abortAssessment = false;
    this.index = 0;
    this.model = options.model;
    Tangerine.activity = "assessment print";
    this.subtestViews = [];
    this.model.subtests.sort();
    return this.model.subtests.each(function(model) {
      return _this.subtestViews.push(new SubtestPrintView({
        model: model,
        parent: _this
      }));
    });
  };

  AssessmentPrintView.prototype.render = function() {
    var currentView,
      _this = this;
    currentView = this.subtestViews[this.index];
    if (this.model.subtests.length === 0) {
      this.$el.append("<h1>Oops...</h1><p>This assessment is blank. Perhaps you meant to add some subtests.</p>");
    } else {
      this.$el.html("        <h1>" + (this.model.get('name')) + "</h1>        <div id='progress'></div>      ");
      this.$el.find('#progress').progressbar({
        value: (this.index + 1) / (this.model.subtests.length + 1) * 100
      });
      currentView.on("rendered", function() {
        return _this.trigger("rendered");
      });
      currentView.on("subRendered", function() {
        return _this.trigger("subRendered");
      });
      currentView.render();
      this.$el.append(currentView.el);
    }
    return this.trigger("rendered");
  };

  return AssessmentPrintView;

})(Backbone.View);
