// Generated by CoffeeScript 1.3.1
var Assessment,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

Assessment = (function(_super) {

  __extends(Assessment, _super);

  Assessment.name = 'Assessment';

  function Assessment() {
    this.fetch = __bind(this.fetch, this);
    return Assessment.__super__.constructor.apply(this, arguments);
  }

  Assessment.prototype.url = 'assessment';

  Assessment.prototype.initialize = function(options) {
    if (options == null) {
      options = {};
    }
    return this.subtests = new Subtests;
  };

  Assessment.prototype.fetch = function(options) {
    var oldSuccess,
      _this = this;
    oldSuccess = options.success;
    options.success = function(model) {
      var allSubtests;
      allSubtests = new Subtests;
      return allSubtests.fetch({
        key: _this.id,
        success: function(collection) {
          _this.subtests = collection;
          _this.subtests.maintainOrder();
          return typeof oldSuccess === "function" ? oldSuccess(_this) : void 0;
        }
      });
    };
    return Assessment.__super__.fetch.call(this, options);
  };

  Assessment.prototype.duplicate = function(assessmentAttributes, subtestAttributes, questionAttributes, callback) {
    var newModel, originalId, questions,
      _this = this;
    originalId = this.id;
    newModel = this.clone();
    newModel.set(assessmentAttributes);
    newModel.set("_id", Utils.guid());
    newModel.save(null, {
      "wait": true
    });
    questions = new Questions;
    return questions.fetch({
      key: this.id,
      success: function(questions) {
        var subtests;
        subtests = new Subtests;
        return subtests.fetch({
          key: originalId,
          success: function(subtests) {
            var filteredSubtests, gridId, i, model, newQuestion, newQuestions, newSubtest, newSubtestId, newSubtests, oldId, question, subtestIdMap, _i, _j, _k, _len, _len1, _len2;
            filteredSubtests = subtests.models;
            subtestIdMap = {};
            newSubtests = [];
            for (i = _i = 0, _len = filteredSubtests.length; _i < _len; i = ++_i) {
              model = filteredSubtests[i];
              newSubtest = model.clone();
              newSubtest.set("assessmentId", newModel.id);
              newSubtestId = Utils.guid();
              subtestIdMap[newSubtest.id] = newSubtestId;
              newSubtest.set("_id", newSubtestId);
              newSubtests.push(newSubtest);
            }
            for (i = _j = 0, _len1 = newSubtests.length; _j < _len1; i = ++_j) {
              model = newSubtests[i];
              gridId = model.get("gridLinkId");
              if ((gridId || "") !== "") {
                model.set("gridLinkId", subtestIdMap[gridId]);
              }
              model.save();
            }
            newQuestions = [];
            for (_k = 0, _len2 = questions.length; _k < _len2; _k++) {
              question = questions[_k];
              newQuestion = question.clone();
              oldId = newQuestion.get("subtestId");
              newQuestion.set("assessmentId", newModel.id);
              newQuestion.set("_id", Utils.guid());
              newQuestion.set("subtestId", subtestIdMap[oldId]);
              newQuestions.push(newQuestion);
              newQuestion.save();
            }
            return callback();
          }
        });
      }
    });
  };

  Assessment.prototype.destroy = function() {
    var assessmentId, questions, subtests;
    assessmentId = this.id;
    subtests = new Subtests;
    subtests.fetch({
      key: assessmentId,
      success: function(collection) {
        var _results;
        _results = [];
        while (collection.length !== 0) {
          _results.push(collection.pop().destroy());
        }
        return _results;
      }
    });
    questions = new Questions;
    questions.fetch({
      key: this.id,
      success: function(collection) {
        var model, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = collection.length; _i < _len; _i++) {
          model = collection[_i];
          _results.push(model.destroy());
        }
        return _results;
      }
    });
    return Assessment.__super__.destroy.call(this);
  };

  return Assessment;

})(Backbone.Model);
