// Generated by CoffeeScript 1.4.0
var DatetimeEditView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

DatetimeEditView = (function(_super) {

  __extends(DatetimeEditView, _super);

  function DatetimeEditView() {
    return DatetimeEditView.__super__.constructor.apply(this, arguments);
  }

  DatetimeEditView.prototype.className = "DatetimeEditView";

  DatetimeEditView.prototype.initialize = function(options) {
    this.model = options.model;
    return this.parent = options.parent;
  };

  DatetimeEditView.prototype.save = function() {};

  DatetimeEditView.prototype.isValid = function() {
    return true;
  };

  return DatetimeEditView;

})(Backbone.View);
