// Generated by CoffeeScript 1.3.3
(function() {
  var DatetimePrintView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DatetimePrintView = (function(_super) {

    __extends(DatetimePrintView, _super);

    function DatetimePrintView() {
      return DatetimePrintView.__super__.constructor.apply(this, arguments);
    }

    DatetimePrintView.prototype.className = "datetime";

    DatetimePrintView.prototype.initialize = function(options) {
      this.model = this.options.model;
      return this.parent = this.options.parent;
    };

    DatetimePrintView.prototype.render = function() {
      this.$el.html("      <form>          <table>            <tr>              <td><label for='year'>Year</label><input id='year' name='year' value='" + year + "'></td>              <td><label for='month'>Month</label><input id='month' type='month' name='month' value='" + month + "'></td>              <td><label for='day'>Day</label><input id='day' type='day' name='day' value='" + day + "'></td>            </tr>          </table>          <label for='time'>Time</label><br><input type='text' id='time' name='time' value='" + time + "'>      </form>      ");
      return this.trigger("rendered");
    };

    return DatetimePrintView;

  })(Backbone.View);

}).call(this);
