// Generated by CoffeeScript 1.4.0
var IdPrintView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

IdPrintView = (function(_super) {

  __extends(IdPrintView, _super);

  function IdPrintView() {
    return IdPrintView.__super__.constructor.apply(this, arguments);
  }

  IdPrintView.prototype.className = "id";

  IdPrintView.prototype.initialize = function(options) {};

  IdPrintView.prototype.render = function() {
    if (this.format === "stimuli") {
      return;
    }
    if (this.format === "backup" || this.format === "content") {
      this.$el.html("          <div class='subtest-title'>" + (this.model.get("name")) + "</div>          <table class='marking-table'>            <tr>              <td style='vertical-align:middle'>" + (this.model.get("name")) + "</td><td class='marking-area'></td>            </tr>          </table>      ");
    }
    return this.trigger("rendered");
  };

  return IdPrintView;

})(Backbone.View);
