// Generated by CoffeeScript 1.3.3
(function() {
  var IdPrintView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  IdPrintView = (function(_super) {

    __extends(IdPrintView, _super);

    function IdPrintView() {
      return IdPrintView.__super__.constructor.apply(this, arguments);
    }

    IdPrintView.prototype.className = "id";

    IdPrintView.prototype.events = {
      'click #generate': 'generate',
      'change #participant_id': 'setValidator'
    };

    IdPrintView.prototype.initialize = function(options) {
      this.model = this.options.model;
      this.parent = this.options.parent;
      return this.validator = new CheckDigit;
    };

    IdPrintView.prototype.render = function() {
      this.$el.html("    <form>      <label for='participant_id'>Random Identifier</label>      <input id='participant_id' name='participant_id'>      <button id='generate' class='command'>Generate</button>      <div class='messages'></div>    </form>");
      return this.trigger("rendered");
    };

    return IdPrintView;

  })(Backbone.View);

}).call(this);
