// Generated by CoffeeScript 1.4.0
var LocationPrintView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LocationPrintView = (function(_super) {

  __extends(LocationPrintView, _super);

  function LocationPrintView() {
    return LocationPrintView.__super__.constructor.apply(this, arguments);
  }

  LocationPrintView.prototype.className = "LocationPrintView";

  LocationPrintView.prototype.initialize = function(options) {
    this.model = this.options.model;
    this.parent = this.options.parent;
    this.levels = this.model.get("levels") || [];
    this.locations = this.model.get("locations") || [];
    if (this.levels.length === 1 && this.levels[0] === "") {
      this.levels = [];
    }
    if (this.locations.length === 1 && this.locations[0] === "") {
      return this.locations = [];
    }
  };

  LocationPrintView.prototype.render = function() {
    if (this.format === "stimuli") {
      return;
    }
    if (this.format === "content") {
      this.$el.html("        School Locations<br/>        Levels: " + this.levels + "<br/>        Available Locations:<br/>        " + (this.locations.join("<br/>")) + "<br/>      ");
    }
    if (this.format === "backup") {
      this.$el.html("          <div class='subtest-title'>" + (this.model.get("name")) + "</div>          <table class='marking-table'>            " + (_(this.levels).map(function(locationLevel) {
        return "                <tr>                  <td style='vertical-align:middle'>" + locationLevel + "</td><td class='marking-area'></td>                </tr>              ";
      }).join("")) + "          </table>      ");
    }
    return this.trigger("rendered");
  };

  return LocationPrintView;

})(Backbone.View);
