// Generated by CoffeeScript 1.4.0
var LocationRunView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LocationRunView = (function(_super) {

  __extends(LocationRunView, _super);

  function LocationRunView() {
    return LocationRunView.__super__.constructor.apply(this, arguments);
  }

  LocationRunView.prototype.events = {
    "click .school_list li": "autofill",
    "keyup input": "showOptions",
    "click .clear": "clearInputs"
  };

  LocationRunView.prototype.initialize = function(options) {
    var i, level, location, locationData, template, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;
    this.model = this.options.model;
    this.parent = this.options.parent;
    this.levels = this.model.get("levels") || [];
    this.locations = this.model.get("locations") || [];
    if (this.levels.length === 1 && this.levels[0] === "") {
      this.levels = [];
    }
    if (this.locations.length === 1 && this.locations[0] === "") {
      this.locations = [];
    }
    this.haystack = [];
    _ref = this.locations;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      location = _ref[i];
      this.haystack[i] = [];
      for (_j = 0, _len1 = location.length; _j < _len1; _j++) {
        locationData = location[_j];
        this.haystack[i].push(locationData.toLowerCase());
      }
    }
    template = "<li data-index='{{i}}'>";
    _ref1 = this.levels;
    for (i = _k = 0, _len2 = _ref1.length; _k < _len2; i = ++_k) {
      level = _ref1[i];
      template += "{{level_" + i + "}}";
      if (i !== this.levels.length - 1) {
        template += " - ";
      }
    }
    template += "</li>";
    return this.li = _.template(template);
  };

  LocationRunView.prototype.clearInputs = function() {
    var i, level, _i, _len, _ref, _results;
    _ref = this.levels;
    _results = [];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      level = _ref[i];
      _results.push(this.$el.find("#level_" + i).val(""));
    }
    return _results;
  };

  LocationRunView.prototype.autofill = function(event) {
    var i, index, level, location, _i, _len, _ref, _results;
    this.$el.find(".autofill").fadeOut(250);
    index = $(event.target).attr("data-index");
    location = this.locations[index];
    _ref = this.levels;
    _results = [];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      level = _ref[i];
      _results.push(this.$el.find("#level_" + i).val(location[i]));
    }
    return _results;
  };

  LocationRunView.prototype.showOptions = function(event) {
    var atLeastOne, field, html, i, isThere, j, needle, otherField, result, results, stack, _i, _j, _k, _l, _len, _len1, _len2, _len3, _m, _ref, _ref1, _ref2;
    needle = $(event.target).val().toLowerCase();
    field = parseInt($(event.target).attr('data-level'));
    for (otherField = _i = 0, _ref = this.haystack.length; 0 <= _ref ? _i <= _ref : _i >= _ref; otherField = 0 <= _ref ? ++_i : --_i) {
      this.$el.find("#autofill_" + otherField).hide();
    }
    atLeastOne = false;
    results = [];
    _ref1 = this.haystack;
    for (i = _j = 0, _len = _ref1.length; _j < _len; i = ++_j) {
      stack = _ref1[i];
      isThere = ~this.haystack[i][field].indexOf(needle);
      if (isThere) {
        results.push(i);
      }
      if (isThere) {
        atLeastOne = true;
      }
    }
    _ref2 = this.haystack;
    for (i = _k = 0, _len1 = _ref2.length; _k < _len1; i = ++_k) {
      stack = _ref2[i];
      for (j = _l = 0, _len2 = stack.length; _l < _len2; j = ++_l) {
        otherField = stack[j];
        if (j === field) {
          continue;
        }
        isThere = ~this.haystack[i][j].indexOf(needle);
        if (isThere && !~results.indexOf(i)) {
          results.push(i);
        }
        if (isThere) {
          atLeastOne = true;
        }
      }
    }
    if (atLeastOne) {
      html = "";
      for (_m = 0, _len3 = results.length; _m < _len3; _m++) {
        result = results[_m];
        html += this.getLocationLi(result);
      }
      this.$el.find("#autofill_" + field).fadeIn(250);
      return this.$el.find("#school_list_" + field).html(html);
    } else {
      return this.$el.find("#autofill_" + field).fadeOut(250);
    }
  };

  LocationRunView.prototype.getLocationLi = function(i) {
    var j, location, templateInfo, _i, _len, _ref;
    templateInfo = {
      "i": i
    };
    _ref = this.locations[i];
    for (j = _i = 0, _len = _ref.length; _i < _len; j = ++_i) {
      location = _ref[j];
      templateInfo["level_" + j] = location;
    }
    return this.li(templateInfo);
  };

  LocationRunView.prototype.render = function() {
    var html, i, level, schoolListElements, _i, _len, _ref;
    schoolListElements = "";
    html = "      <button class='clear command'>" + (t('clear')) + "</button>      ";
    _ref = this.levels;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      level = _ref[i];
      html += "        <div class='label_value'>          <label for='level_" + i + "'>" + level + "</label><br>          <input data-level='" + i + "' id='level_" + i + "' value=''>        </div>        <div id='autofill_" + i + "' class='autofill' style='display:none'>          <h2>" + (t('select one from autofill list')) + "</h2>          <ul class='school_list' id='school_list_" + i + "'>          </ul>        </div>    ";
    }
    this.$el.html(html);
    this.trigger("rendered");
    return this.trigger("ready");
  };

  LocationRunView.prototype.getResult = function() {
    var i, level;
    return {
      "labels": (function() {
        var _i, _len, _ref, _results;
        _ref = this.levels;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          level = _ref[_i];
          _results.push(level.replace(/[\s-]/g, "_"));
        }
        return _results;
      }).call(this),
      "location": (function() {
        var _i, _len, _ref, _results;
        _ref = this.levels;
        _results = [];
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          level = _ref[i];
          _results.push($.trim(this.$el.find("#level_" + i).val()));
        }
        return _results;
      }).call(this)
    };
  };

  LocationRunView.prototype.getSkipped = function() {
    var i, level;
    return {
      "labels": (function() {
        var _i, _len, _ref, _results;
        _ref = this.levels;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          level = _ref[_i];
          _results.push(level.replace(/[\s-]/g, "_"));
        }
        return _results;
      }).call(this),
      "location": (function() {
        var _i, _len, _ref, _results;
        _ref = this.levels;
        _results = [];
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          level = _ref[i];
          _results.push("skipped");
        }
        return _results;
      }).call(this)
    };
  };

  LocationRunView.prototype.isValid = function() {
    var input, _i, _len, _ref;
    this.$el.find(".message").remove();
    _ref = this.$el.find("input");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      input = _ref[_i];
      if ($(input).val() === "") {
        return false;
      }
    }
    return true;
  };

  LocationRunView.prototype.showErrors = function() {
    var input, _i, _len, _ref, _results;
    _ref = this.$el.find("input");
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      input = _ref[_i];
      if ($(input).val() === "") {
        _results.push($(input).after(" <span class='message'>" + ($('label[for=' + $(input).attr('id') + ']').text()) + " " + (t('cannot be empty')) + "</span>"));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  LocationRunView.prototype.getSum = function() {
    var $input, counts, input, _i, _len, _ref;
    counts = {
      correct: 0,
      incorrect: 0,
      missing: 0,
      total: 0
    };
    _ref = this.$el.find("input");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      input = _ref[_i];
      $input = $(input);
      if (($input.val() || "") !== "") {
        counts['correct'] += 1;
      }
      if (false) {
        counts['incorrect'] += 0;
      }
      if (($input.val() || "") === "") {
        counts['missing'] += 1;
      }
      if (true) {
        counts['total'] += 1;
      }
    }
    return {
      correct: counts['correct'],
      incorrect: counts['incorrect'],
      missing: counts['missing'],
      total: counts['total']
    };
  };

  return LocationRunView;

})(Backbone.View);
