// Generated by CoffeeScript 1.4.0
var Teacher, Teachers,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Teacher = (function(_super) {

  __extends(Teacher, _super);

  function Teacher() {
    return Teacher.__super__.constructor.apply(this, arguments);
  }

  Teacher.prototype.url = "teacher";

  return Teacher;

})(Backbone.Model);

Teachers = (function(_super) {

  __extends(Teachers, _super);

  function Teachers() {
    return Teachers.__super__.constructor.apply(this, arguments);
  }

  Teachers.prototype.model = Teacher;

  Teachers.prototype.url = "teacher";

  return Teachers;

})(Backbone.Collection);
