// Generated by CoffeeScript 1.7.1
(function(doc) {
  var id;
  if (doc.collection !== 'question') {
    return;
  }
  id = doc.assessmentId || doc.curriculumId;
  if (id != null) {
    return emit(id, doc);
  }
});
