// Generated by CoffeeScript 1.4.0
var Log, LogView, Logs,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Log = (function(_super) {

  __extends(Log, _super);

  function Log() {
    return Log.__super__.constructor.apply(this, arguments);
  }

  Log.prototype.url = "log";

  Log.prototype.initialize = function() {
    if (this.get("_id") !== this.calcName()) {
      return this.ensure();
    }
  };

  Log.prototype.ensure = function(callback) {
    var d,
      _this = this;
    d = new Date();
    this.set({
      "_id": this.calcName(),
      "year": d.getFullYear(),
      "month": d.getMonth(),
      "date": d.getDate(),
      "user": Tangerine.user.name
    });
    return this.save(null, {
      success: function() {
        return typeof callback === "function" ? callback() : void 0;
      },
      error: function() {
        return _this.fetch({
          success: function() {
            return _this.save({
              succes: function() {
                return typeof callback === "function" ? callback() : void 0;
              }
            });
          },
          error: function() {
            return typeof callback === "function" ? callback() : void 0;
          }
        });
      }
    });
  };

  Log.prototype.app = function(code, details) {
    if (code == null) {
      code = "";
    }
    if (details == null) {
      details = "";
    }
    if (Tangerine.settings.get("context") === "server") {
      return;
    }
    if (!~Tangerine.settings.get("log").indexOf("app")) {
      return;
    }
    return Tangerine.log.add({
      "type": "app",
      "code": code,
      "details": details,
      "timestamp": (new Date()).getTime()
    });
  };

  Log.prototype.db = function(code, details) {
    if (code == null) {
      code = "";
    }
    if (details == null) {
      details = "";
    }
    if (Tangerine.settings.get("context") === "server") {
      return;
    }
    if (!~Tangerine.settings.get("log").indexOf("db")) {
      return;
    }
    return Tangerine.log.add({
      "type": "db",
      "code": code,
      "details": details,
      "timestamp": (new Date()).getTime()
    });
  };

  Log.prototype.ui = function(code, details) {
    if (code == null) {
      code = "";
    }
    if (details == null) {
      details = "";
    }
    if (Tangerine.settings.get("context") === "server") {
      return;
    }
    if (!~Tangerine.settings.get("log").indexOf("ui")) {
      return;
    }
    return Tangerine.log.add({
      "type": "ui",
      "code": code,
      "details": details,
      "timestamp": (new Date()).getTime()
    });
  };

  Log.prototype.err = function(code, details) {
    if (code == null) {
      code = "";
    }
    if (details == null) {
      details = "";
    }
    if (Tangerine.settings.get("context") === "server") {
      return;
    }
    return !~Tangerine.settings.get("log").indexOf("err");
    return Tangerine.log.add({
      "type": "err",
      "code": code,
      "details": details,
      "timestamp": (new Date()).getTime()
    });
  };

  Log.prototype.add = function(logEvent) {
    var logEvents,
      _this = this;
    logEvents = this.getArray("logEvents");
    logEvents.push(logEvent);
    this.set("logEvents", logEvents);
    return this.ensure(function() {
      return Tangerine.log.save;
    });
  };

  Log.prototype.calcName = function() {
    var d, user;
    d = new Date();
    user = Tangerine.user.name != null ? Tangerine.user.name : "not-signed-in";
    return hex_sha1("" + user + "_" + (d.getFullYear()) + "-" + (d.getMonth()) + "-" + (d.getDate()));
  };

  return Log;

})(Backbone.Model);

Logs = (function(_super) {

  __extends(Logs, _super);

  function Logs() {
    return Logs.__super__.constructor.apply(this, arguments);
  }

  Logs.prototype.url = "log";

  Logs.prototype.model = Log;

  Logs.prototype.comparator = function(model) {
    return model.get("timestamp");
  };

  return Logs;

})(Backbone.Collection);

LogView = (function(_super) {

  __extends(LogView, _super);

  function LogView() {
    this.render = __bind(this.render, this);
    return LogView.__super__.constructor.apply(this, arguments);
  }

  LogView.prototype.className = "LogView";

  LogView.prototype.initialize = function(options) {
    var _this = this;
    this.logs = options.logs;
    return this.logs.on("all", function() {
      return _this.render();
    });
  };

  LogView.prototype.render = function() {
    var html,
      _this = this;
    html = "";
    this.logs.each(function(log) {
      var k, oneEvent, v, _i, _len, _ref, _ref1;
      html += "<b>User</b> " + (log.get("user")) + "<br><br>";
      html += "<table><tr>";
      _ref = log.get("logEvents")[0];
      for (k in _ref) {
        v = _ref[k];
        html += "<th>" + k + "</th>";
      }
      html += "</tr>";
      _ref1 = log.get("logEvents");
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        oneEvent = _ref1[_i];
        html += "<tr>";
        for (k in oneEvent) {
          v = oneEvent[k];
          if (k === "timestamp") {
            v = (new Date(parseInt(v))).toString();
          }
          html += "<td>" + v + "</td>";
        }
        html += "</tr>";
      }
      return html += "</table>";
    });
    this.$el.html(html);
    return this.trigger("rendered");
  };

  return LogView;

})(Backbone.View);
