// Generated by CoffeeScript 1.4.0
var AdminView,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

AdminView = (function(_super) {

  __extends(AdminView, _super);

  function AdminView() {
    this.render = __bind(this.render, this);
    return AdminView.__super__.constructor.apply(this, arguments);
  }

  AdminView.prototype.className = "AdminView";

  AdminView.prototype.render = function() {
    var _this = this;
    return $.couch.allDbs({
      success: function(databases) {
        var groups;
        groups = _(databases).filter(function(database) {
          return database.match(/^group-/);
        });
        _this.$el.html("          TODO: <button>Replicate from update database to all existing groups (design doc, views, etc)</button>          <h2>Active Groups</h2>        ");
        _(groups).each(function(group) {
          var groupName;
          groupName = group.replace(/group-/, "");
          return $.couch.db(group).view(Tangerine.design_doc + "/resultCount", {
            group: true,
            success: function(resultCounts) {
              _this.$el.append("                <h2>" + groupName + "</h2>                <table id='" + group + "'>                  <tr>                    <td>Version</td><td id='" + group + "-version'></td>                  </tr>                  <tr>                    <td>Last Result</td><td id='" + group + "-last-result'></td>                  </tr>                  <tr>                    <td>Total Assessments</td><td id='" + group + "-total-assessments'></td>                  </tr>                  <tr>                    <td>Total Results</td><td id='" + group + "-total-results'></td>                  </tr>                </table>                <button onClick='document.location='>" + groupName + " Dashboard</button><br/>                <button onClick='$(\"#" + group + "-details\").toggle()'>Details</button>                <table style='display:none' id='" + group + "-details'>                  <thead>                    <th>Assessment</th>                    <th>Number of Results</th>                  </thead>                  " + (_(resultCounts.rows).map(function(resultCount) {
                return "                    <tr>                      <td id='" + resultCount.key + "'>" + resultCount.key + "</td><td class='result-count'>" + resultCount.value + "</td>                    </tr>                    ";
              }).join("")) + "                </table>              ");
              $("#" + group + "-total-assessments").html(_this.$el.find("table#" + group + "-details tr").length);
              $("#" + group + "-total-results").html(_(_this.$el.find(".result-count")).reduce((function(total, amount) {
                return total += parseInt($(amount).text());
              }), 0));
              $.couch.db(group).view(Tangerine.design_doc + "/resultSummaryByAssessmentId", {
                group: true,
                success: function(mostRecentEndTime) {
                  return _(mostRecentEndTime.rows).each(function(row) {
                    if (row.value != null) {
                      return $("#" + group + "-last-result").html("                        <span data-end-time='" + row.value + "'>" + (moment(row.value).fromNow()) + "</span>                      ");
                    }
                  });
                }
              });
              $.ajax("/" + group + "/_design/" + Tangerine.design_doc + "/js/version.js", {
                dataType: "text",
                success: function(result) {
                  return $("#" + group + "-version").html(result.match(/"(.*)"/)[1]);
                }
              });
              return _.each(resultCounts.rows, function(row) {
                if (row.key == null) {
                  return;
                }
                return $.couch.db(group).openDoc(row.key, {
                  success: function(result) {
                    return $("#" + row.key).html(result.name);
                  },
                  error: function(result) {
                    return $("#" + row.key).html("Unknown assessment");
                  }
                });
              });
            }
          });
        });
        return _this.trigger("rendered");
      }
    });
  };

  return AdminView;

})(Backbone.View);
