// Generated by CoffeeScript 1.7.1
(function(doc) {
  var total;
  if (doc.collection === 'result') {
    total = doc.subtestData[doc.subtestData.length - 1].timestamp - doc.start_time;
    return emit(doc.assessmentId, total);
  }
});
